@startuml

title "Flujo Inicio Chat de Usuarios"

actor User as user

participant "Client" as client
participant "API Gateway" as gateway
participant "AUTH Service" as auth

client-[#blue]>gateway: HTTP POST\n(JWT)
gateway-[#purple]>auth: Delega validación\n(JWT)
auth->auth: Verifica JWT

alt Incorrecto
  auth-[#purple]>gateway: Incorrecto
  gateway-[#blue]>client: HTTP 401\nNo Autorizado

else Correcto
  auth-[#purple]>gateway: Correcto
  gateway->gateway: Genera session_id
  gateway->gateway: Registra session_id\ny Conexión SSE
  gateway-[#blue]>client: HTTP 202\n(Cabeceras SSE, session_id)
  
  note right of client
    Se inicia conexión SSE cliente-servidor
    que se mantiene abierta.
  end note
  
end

legend top
  <color:blue>REST/HTTP</color>
  <color:purple>gRPC</color>
end legend

@end uml