@startuml

title "Flujo de Login de Usuarios"

actor User as user
participant "Client" as client
participant "API Gateway" as gateway
participant "AUTH Service" as auth
participant "DB Service" as db
database "UserDB" as userDB

user->client: Introduce\ncredenciales
client-[#blue]>gateway: HTTP POST\n(Username, Password)
gateway-[#purple]>auth: Delega validación\n(Username, Password)
auth-[#purple]>db: Solicita usuario\n(Username)
db->userDB: Consulta usuario
userDB->db: Devuelve datos\n(Hash, Salt)
db-[#purple]>auth: Devuelve datos\n(Hash, Salt)

auth->auth: Verifica password

alt Incorrecto
  auth-[#purple]>gateway: Incorrecto
  gateway-[#blue]>client: HTTP 401\nNo Autorizado
else Correcto
  auth->auth: Genera JWT
  auth-[#purple]>gateway: Correcto
  gateway-[#blue]>client: HTTP 200\n(JWT)
end

client->user: Muestra resultado\nde login

legend top
  <color:blue>REST/HTTP</color>
  <color:purple>gRPC</color>
end legend

@enduml