# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rag.service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'rag.service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11rag.service.proto\x12\x05proto\"\x1f\n\x0e\x43ontextRequest\x12\r\n\x05query\x18\x01 \x01(\t\"\x1f\n\x0f\x43ontextResponse\x12\x0c\n\x04json\x18\x01 \x01(\t2I\n\nRagService\x12;\n\nGetContext\x12\x15.proto.ContextRequest\x1a\x16.proto.ContextResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rag.service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONTEXTREQUEST']._serialized_start=28
  _globals['_CONTEXTREQUEST']._serialized_end=59
  _globals['_CONTEXTRESPONSE']._serialized_start=61
  _globals['_CONTEXTRESPONSE']._serialized_end=92
  _globals['_RAGSERVICE']._serialized_start=94
  _globals['_RAGSERVICE']._serialized_end=167
# @@protoc_insertion_point(module_scope)
