@startuml

title "Flujo de creación de chat de Usuario"

legend top
Leyenda:
- <color:blue>REST</color> = comunicación HTTP
- <color:purple>gRPC</color> = comunicación gRPC
- <color:red>flow</color> = flujo secundario
end legend

actor User as user
participant "Client" as client
participant "API\nGateway" as gateway
participant "AUTH\nService" as auth

participant "CHAT Service" as chat

database "Chat\nCaché" as chatCache
database "Chat\nDB" as chatDB


== Notifica crear chat  ==

user->client: Notifica creación de chat
client-[#blue]>gateway: POST /chat/new\n{ACCESS_TOKEN}


== Creación del chat ==

gateway-[#purple]>chat: Crea chat\n{ACCESS_TOKEN}

chat-[#red]>chat: Gestion de JWT

note right chat
  Este flujo valida y gestiona los tokens.
end note

chat->chatDB: INSERT chat\n{user_id}
chat->chat: Crea directorio\ny fichero
chat->chatCache: async Crea nuevo registro\n{chat_id}
chat-[#purple]>gateway: Payload

note right gateway
  Payload
  {
    "status": true
    "code": 200
    "chat_id": 123456789
  }
end note

gateway-[#blue]>client: 200 - OK\n{chat_id}


@enduml