@startuml

title "Flujo de cierre de sesión de Usuario"

legend top
Leyenda:
- <color:blue>REST</color> = comunicación HTTP
- <color:purple>gRPC</color> = comunicación gRPC
end legend

actor User as user
participant "Client" as client
participant "API\nGateway" as gateway
participant "AUTH\nService" as auth

database "Token\nCaché" as tokenCache
database "User\nDB" as userDB


== Usuario solicita logout ==

user->client: Notifica cerrar sesión
client-[#blue]>gateway: POST /logout\n{REFRESH_TOKEN}


== Invalidación de tokens ==

gateway-[#purple]>auth: Invalida tokens\n{REFRESH_TOKEN}

auth->auth: Comprueba firma\nde ACCESS_TOKEN

alt ACCESS_TOKEN Modificado
  auth->auth: Comprueba REFRESH_TOKEN
  
  alt REFRESH_TOKEN Inválido
    auth-[#purple]->gateway: Payload
    
    note right gateway
    Payload:
    {
      "status": False
      "code": 401
    }
    end note
    
    gateway-[#blue]>client: 401 - No autorizado.
    
  else REFRESH_TOKEN Válido
    auth->tokenCache: DEL token\n{REFRESH_TOKEN}
    auth->userDB: DELETE token\n{REFRESH_TOKEN}
    
    auth-[#purple]>gateway: Payload
    
    note right gateway
    Payload:
    {
      "status": True
      "code": 200
    }
    end note
    
    gateway-[#blue]>client: 200 - OK
    
  end

else ACCESS_TOKEN No Modificado
    auth->tokenCache: DEL token\n{REFRESH_TOKEN}
    auth->userDB: DELETE token\n{REFRESH_TOKEN}
    
    auth-[#purple]>gateway: Payload
    
    note right gateway
    Payload:
    {
      "status": True
      "code": 200
    }
    end note
    
    gateway-[#blue]>client: 200 - OK
    
end

@enduml